server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ocean
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: edwin
    password: port3306
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#    database: 0

#logging:
#  level: info

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
