server:
  port: 8080
  servlet:
    session:
      timeout: 1m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ocean
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: edwin
    password: port3306
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
  security:
    user:
      name: user
      password: user
  session:
    timeout: 1m
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#    database: 0

#logging:
#  level: info


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml

jwt:
  header: Authorization
  expire: 604800 # 7 天 (秒)
  secret: insei43l0ijomis4j4k3llp2309r431w